### ISSUE TITLE
nsqadmin: non admin user can delete the topic on a node

### ISSUE THREAD

**Issue by guishoudaoge** [nsqio/nsq#1390]
Hi Team

On the nsqadmin UI page, Non admin user can see the delete icon and delete the topic on a node successfully

tombstoneNodeForTopicHandler  is not protected by isAuthorizedAdminRequest

Thanks
/Joe

**Comment by mreiferson** [comment]
Yep, it also doesn't present a confirmation dialog.

**Comment by SandroJijavadze** [comment]
If admin-user option is set on nsqadmin I can't see option to delete user with non-admin user.

**Comment by suenchunyu** [comment]
@mreiferson I cloned the latest master branch and tried to delete the topic and channel with the admin option enabled, the API responds `FORBEDDEN`, it looks like this bug has been fixed and this issue should be closed.

**Comment by mreiferson** [comment]
@suenchunyu the request handler `tombstoneNodeForTopicHandler` is still missing the admin check, so it can't be fixed...

**Comment by suenchunyu** [comment]
> @suenchunyu the request handler `tombstoneNodeForTopicHandler` is still missing the admin check, so it can't be fixed...

Well, I think it's enough to add pre-check is an authorized admin request before parsing request body, right?
